#!/usr/bin/env python3
"""Generate twiddle factor ROM for radix-2 SDF pipelined FFT.

Each stage k needs 2^k twiddle factors:
  W_N^(b * 2^(log2(N)-1-k))  for b = 0, 1, ..., 2^k-1

Stage 0: always W=1 (no multiply needed) — generates empty ROM.

Usage:
  python3 gen_twiddle.py 64 16 > ../rtl/twiddle_rom.v
  python3 gen_twiddle.py 64 16 --cpp  > twiddle.h    # C header for testbench
"""

import math
import sys


def qformat(val, width):
    """Convert float to Q1.(WIDTH-1) fixed-point integer."""
    maxval = (1 << (width - 1)) - 1
    clamped = max(-1.0, min(1.0 - 1.0 / maxval, val))
    return int(round(clamped * maxval))


def gen_verilog(N, width):
    """Generate Verilog twiddle ROM module."""
    log2N = int(math.log2(N))
    total_words = 0

    lines = []
    lines.append(f"// Twiddle factor ROM — {N}-point FFT, {width}-bit Q1.{width-1}")
    lines.append("// Auto-generated by gen_twiddle.py")
    lines.append(f"// Total words: {N - 1}")
    lines.append("")
    lines.append(f"module twiddle_rom #(")
    lines.append(f"    parameter N = {N},")
    lines.append(f"    parameter WIDTH = {width}")
    lines.append(") (")
    lines.append("    input  wire [$clog2(N)-1:0]  addr,")
    lines.append("    output reg  [2*WIDTH-1:0]    dout    // {im[WIDTH-1:0], re[WIDTH-1:0]}")
    lines.append(");")
    lines.append("")
    lines.append("    always @(*) begin")
    lines.append("        case (addr)")

    idx = 0
    for stage in range(1, log2N):  # stage 0 has W=1, no ROM needed
        n_tw = 1 << stage  # 2^stage twiddle factors
        for b in range(n_tw):
            angle = -2 * math.pi * b * (1 << (log2N - 1 - stage)) / N
            re = qformat(math.cos(angle), width)
            im = qformat(math.sin(angle), width)
            re_hex = re & ((1 << width) - 1)
            im_hex = im & ((1 << width) - 1)
            combined = (im_hex << width) | re_hex
            lines.append(f"            {width}'d{idx}: dout = {2*width}'h{combined:0{2*width//4}x};")
            idx += 1
            total_words += 1

    lines.append(f"            default: dout = {2*width}'h0;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("")
    lines.append("endmodule")

    return "\n".join(lines), total_words


def gen_c_header(N, width):
    """Generate C header with twiddle constants for testbench."""
    log2N = int(math.log2(N))
    lines = []
    lines.append(f"// Twiddle factors for {N}-point FFT, {width}-bit Q1.{width-1}")
    lines.append(f"// Auto-generated by gen_twiddle.py")
    lines.append("")

    idx = 0
    for stage in range(1, log2N):
        n_tw = 1 << stage
        lines.append(f"// Stage {stage} ({n_tw} twiddles)")
        lines.append(f"static const int16_t twiddle_s{stage}[{n_tw}][2] = {{")
        for b in range(n_tw):
            angle = -2 * math.pi * b * (1 << (log2N - 1 - stage)) / N
            re = qformat(math.cos(angle), width)
            im = qformat(math.sin(angle), width)
            lines.append(f"    {{{re}, {im}}},")
            idx += 1
        lines.append("};")
        lines.append("")

    return "\n".join(lines), idx


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "64"
    width = int(sys.argv[2]) if len(sys.argv) > 2 else 16
    cpp_flag = "--cpp" in sys.argv

    try:
        N = int(mode)
    except ValueError:
        print(f"Usage: {sys.argv[0]} <N> [width] [--cpp]", file=sys.stderr)
        sys.exit(1)

    if cpp_flag:
        code, total = gen_c_header(N, width)
    else:
        code, total = gen_verilog(N, width)

    # Print header comment
    if cpp_flag:
        print(f"// Total twiddle words: {total}")
    else:
        pass  # already in header

    print(code, end="")

    if not cpp_flag:
        print(f"\n// Total twiddle words: {total}")
