#!/usr/bin/env python3
"""Generate twiddle factor ROM for FFT."""

import math
import sys

def gen_twiddle(size, width=16):
    """Generate Verilog case statement for twiddle ROM."""
    print(f"// Twiddle ROM — {size}-point FFT, {width}-bit")
    print(f"// Auto-generated by gen_twiddle.py")
    for k in range(size // 2):
        angle = -2 * math.pi * k / size
        re = int(math.cos(angle) * (2**(width-1) - 1))
        im = int(math.sin(angle) * (2**(width-1) - 1))
        print(f"    {k}: twiddle = {{{width}'d{im}, {width}'d{re}}};")

if __name__ == "__main__":
    size = int(sys.argv[1]) if len(sys.argv) > 1 else 64
    width = int(sys.argv[2]) if len(sys.argv) > 2 else 16
    gen_twiddle(size, width)
